const reviews = [
  {
    initials: "ح",
    nameAr: "حسام محمود",
    nameEn: "Hossam Mahmoud",
    cityAr: "القاهرة",
    cityEn: "Cairo",
    stars: 5,
    textAr: "بصراحة تجربة ممتازة في قرية غزالة، الشاليه كان نضيف جداً والإطلالة حلوة. الحجز كان سريع والتعامل محترم جداً",
    textEn: "Honestly a great experience in Ghazala. The chalet was very clean and the view was nice. Booking was smooth and the service was professional",
    gradient: "linear-gradient(135deg,#4FC3F7,#0288D1)",
  },
  {
    initials: "ر",
    nameAr: "ريم أحمد",
    nameEn: "Reem Ahmed",
    cityAr: "الإسكندرية",
    cityEn: "Alexandria",
    stars: 4,
    textAr: "المكان حلو وهادي في غزالة، مناسب للعائلات جداً. كان فيه تأخير بسيط في الاستلام بس اتحل بسرعة",
    textEn: "Nice and calm place in Ghazala, very suitable for families. There was a small delay in check-in but it was handled quickly",
    gradient: "linear-gradient(135deg,#E8D8C3,#C4A882)",
  },
  {
    initials: "م",
    nameAr: "محمد طارق",
    nameEn: "Mohamed Tarek",
    cityAr: "المنصورة",
    cityEn: "Mansoura",
    stars: 5,
    textAr: "من أحسن التجارب في الساحل، الشاليه مطابق للصور بالظبط والمكان نظيف جداً. أكيد هكررها تاني",
    textEn: "One of the best North Coast experiences. The chalet matches the photos exactly and it's very clean. Definitely doing it again",
    gradient: "linear-gradient(135deg,#4FC3F7,#25D366)",
  },
  {
    initials: "س",
    nameAr: "سارة خالد",
    nameEn: "Sara Khaled",
    cityAr: "الجيزة",
    cityEn: "Giza",
    stars: 4,
    textAr: "الشاليه في غزالة كان حلو جداً وقريب من البحر، بس كنت أتمنى المطبخ يكون مجهز أكتر شوية",
    textEn: "The chalet in Ghazala was really nice and close to the beach, but I wish the kitchen was a bit more equipped",
    gradient: "linear-gradient(135deg,#FFB74D,#F57C00)",
  },
  {
    initials: "أ",
    nameAr: "احمد عادل",
    nameEn: "Ahmed Adel",
    cityAr: "القاهرة",
    cityEn: "Cairo",
    stars: 3,
    textAr: "التجربة كويسة بشكل عام، المكان حلو بس كان فيه زحمة شوية في الويك إند. مناسب لو رايح في وقت هادي",
    textEn: "Overall a good experience. The place is nice but it was a bit crowded on weekends. Better to go on quieter days",
    gradient: "linear-gradient(135deg,#EF5350,#C62828)",
  },
  {
    initials: "ن",
    nameAr: "ندى حمدي",
    nameEn: "Nada Hamdi ",
    cityAr: "الاسكندرية",
    cityEn: "Alexandria",
    stars: 5,
    textAr: "حبيت جداً الإقامة في غزالة، المكان نضيف والخدمة سريعة. مناسب جداً لبنات أو عائلات",
    textEn: "Loved staying in Ghazala. Clean place and fast service. Very suitable for girls or families",
    gradient: "linear-gradient(135deg,#BA68C8,#7B1FA2)",
  },
];